export const REQUEST_IMAGE_GALLERY = 'REQUEST_IMAGE_GALLERY';
export const RECEIVE_IMAGE_GALLERY = 'RECEIVE_IMAGE_GALLERY';
export const RECEIVE_IMAGE_GALLERY_ERROR = 'RECEIVE_IMAGE_GALLERY_ERROR';

export const REQUEST_IMAGE_OF_THE_DAY = 'REQUEST_IMAGE_OF_THE_DAY';
export const RECEIVE_IMAGE_OF_THE_DAY = 'RECEIVE_IMAGE_OF_THE_DAY';
export const RECEIVE_IMAGE_OF_THE_DAY_ERROR = 'RECEIVE_IMAGE_OF_THE_DAY_ERROR';